Mendix/src/com/mendix/test/MaterialScript.java

changed material scripy

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/page/VendorPage_NAV.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/src/com/mendix/test/VendorScript_NAV.java
Mendix/src/com/mendix/util/DataProviderUtil.java
Mendix/suite/scenarios/Change Vendor global and local with Rejections and Discard NAV.xml

committing New Scenario of Avanica

Change vendor Global local nav

---

Mendix/src/com/mendix/page/BasePage.java
Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/src/com/mendix/tool/PageContainer.java
Mendix/suite/scenarios/Extend Material Global and Local from SAP to  NAV with Rejections(With Local data adding).xml
Mendix/suite/scenarios/Extend Material Global and Local from SAP to  NAV(With Local data adding).xml
Mendix/suite/scenarios/Extend Material Global, Local  for JDE  to Nav(Diff. Target System).xml

Committing Scripts with added code and corrections

Committing Scripts

---

Mendix/suite/scenarios/Extend Material Global and Local from SAP to  NAV with Rejections and Discard(With Local data adding).xml

Committing Reject and Discard script for material Extend Nav

Committing Reject and Discard code for Nav Material Extend

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/Extend Material Global and Local from SAP to  NAV with Rejections(With Local data adding).xml
Mendix/suite/scenarios/Extend Vendor Global and Local from JDE to  NAV(With Local data adding).xml
Mendix/suite/scenarios/Extend Vendor Global and Local from SAP to  NAV(With Local data adding).xml

Uft improvements

---

Mendix/suite/scenarios/32Create with ref Global Only - SAP Direct Copy with Rejections.xml
Mendix/suite/scenarios/33Create with ref Global and Local- JDE Direct Copy.xml
Mendix/suite/scenarios/34Create with ref Global and local - NAV Direct Copy.xml
Mendix/suite/scenarios/35Create_with_ref_Global_and_Local - Edit data and delete Plants_JDE.xml
Mendix/suite/scenarios/37Create_with_ref_Global_and_local(Material) - JDE Direct Copy with rejections .xml
Mendix/suite/scenarios/38Create with ref Global and local - NAV Direct Copy with rejections.xml

Merging hand off scenarios as of 21/3

Scenarios for handoff

---

Mendix/suite/scenarios/5.Change _vendor_global _Only.xml
Mendix/suite/scenarios/73Extend Material Global and Local from SAP to  NAV(With Local data adding).xml
Mendix/suite/scenarios/74Extend Material Global and Local from SAP to  NAV with Rejections(With Local data adding).xml

Change in scripts with improvements

---

Mendix/src/com/mendix/tool/Sync.java

Improved Sync file

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/ProceesInfoPage.java
Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/page/VendorPage_NAV.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/src/com/mendix/test/VendorScript_NAV.java
Mendix/suite/scenarios/87Change Vendor global and local with Rejections and Discard NAV.xml

changes done in change vendor global local nav

Changes in Change Vendor Global Local Nav

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/36Create with ref Global and local - Edit Global and Local Data_NAV.xml
Mendix/suite/scenarios/49Extend Material Global, Local  for JDE  to Nav(Diff. Target System).xml
Mendix/suite/scenarios/73Extend Material Global and Local from SAP to  NAV(With Local data adding).xml
Mendix/suite/scenarios/74Extend Material Global and Local from SAP to  NAV with Rejections(With Local data adding).xml
Mendix/suite/scenarios/75Create Material with Questionnaire only Global - SAP Duplicate Found Extend Selected.xml

Extend material flows from SAP to NAV

Committing changes for extend material flows from SAP to NAV

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_JDE_Page.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/page/ProceesInfoPage.java
Mendix/src/com/mendix/test/MaterialChangeScript.java
Mendix/src/com/mendix/test/MaterialJDEScript.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/suite/scenarios/96Extend Material Global and Local with Rejections for JDE (Extend KH01 Opco to SG04).xml

Code for updated scripts

---

Mendix/suite/scenarios/70Extend Vendor Global and Local from SAP to  NAV(With Local data adding).xml

Missing flow from suite

---

Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/suite/scenarios/8.Create_Material_Global_and_Local_for_nav_Duplicate_not_Found.xml

Committing create material corrections

Create Material corrections

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_JDE_Page.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/page/ProceesInfoPage.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/suite/scenarios/93Create Mat. with Ref save as draft global and local  - Direct Copy_JDE .xml

Changes done in Create Material Save As Draft Direct copy JDE

Create Material with Reference Save As Draft JDE

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/suite/scenarios/8.Create_Material_Global_and_Local_for_nav_Duplicate_not_Found.xml

Code fix for process information

Pushing code fix

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialNavScript.java

Fix for process infor check

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/8.Create_Material_Global_and_Local_for_nav_Duplicate_not_Found.xml

Committing fix for process information check extend after all levels

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/LoginScript.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/8.Create_Material_Global_and_Local_for_nav_Duplicate_not_Found.xml

Committing Create Material Flow Nav Smooth flow

Sai create flows 2.4.19

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/src/com/mendix/test/VendorScript_NAV.java
Mendix/src/com/mendix/util/DataProviderUtil.java

Committing improvements to scripts

committing improvements for scripts

---

Mendix/src/com/mendix/page/ProceesInfoPage.java
Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/LoginScript.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/22.Create_Vendor_with_Questionnaire_with_Global_and_Local_NAV.xml
Mendix/suite/scenarios/8.Create_Material_Global_and_Local_for_nav_Duplicate_not_Found.xml

Committing improvements for Create vendor and process infor check

Committing Create vendor flow and few improvements for scripts

---

Mendix/suite/scenarios/22.Create_Vendor_with_Questionnaire_with_Global_and_Local_NAV.xml

Committing 22 code without comments

---

Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/23.Create_Vendor_with_Questionnaire_with_Global_and_Local_with_Rejections_NAV.xml

Committing rejections improvements

---

Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/23.Create_Vendor_with_Questionnaire_with_Global_and_Local_with_Rejections_NAV.xml

Committing vendor create flow with rejections

Vendor create flow with rejections

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/ProceesInfoPage.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/10.Create_Material_with_Questionnaire_only_Global_with_Rejections.xml

Done changes in Create material sap with rejections

Create Material with rejections

---

Mendix/suite/scenarios/23.Create_Vendor_with_Questionnaire_with_Global_and_Local_with_Rejections_NAV.xml

Committing minor improvement

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialScript.java

Committing improvements to Duplicate check added time to resolve sync issue

Sai flows 5.4.19

---

Mendix/src/com/mendix/page/ProceesInfoPage.java

Improved Process Infor Search

---

Mendix/src/com/mendix/page/Material_Change_Page.java
Mendix/src/com/mendix/test/MaterialChangeScript.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/3.Change_Material_global_only.xml

Done changes in change material

Change Material Global only SAP

---

Mendix/suite/scenarios/45Extend same target system - Extend Global for SAP.xml

Committing improved code for Extend same target systems

Committing improved code for Extend same target system SAP

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_Change_Page.java
Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/page/VendorPage_NAV.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/src/com/mendix/test/VendorScript_NAV.java
Mendix/suite/scenarios/25Create_Vendor_with_Questionnaire_with_Global_and_Local_and_Bank_NAV.xml

Create Vendor with Bank data

---

Mendix/src/com/mendix/page/Material_Change_Page.java
Mendix/src/com/mendix/test/MaterialChangeScript.java
Mendix/suite/scenarios/1.Change _Material_global_and_local_for_NAV.xml

Committing change Nav Script and needs more improvements to stebilize the script

Committing change Nav script and needs more improvements yet to be done

---

Mendix/suite/scenarios/7.Create_Material_Global_and_Local_for_JDE.xml

Changes in XML

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/suite/scenarios/1.Change _Material_global_and_local_for_NAV.xml

Sai flows 9.4.19

---

Mendix/src/com/mendix/page/HomePage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_Change_Page.java
Mendix/src/com/mendix/page/Material_JDE_Page.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/test/MaterialChangeScript.java
Mendix/src/com/mendix/test/MaterialJDEScript.java
Mendix/suite/scenarios/2.Change_Material_global_and_local_JDE.xml

Change material JDE

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/12.Create Material with Save as Draft only Global.xml

Create Material Save As Draft

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialChangeScript.java
Mendix/src/com/mendix/tool/Sync.java
Mendix/suite/scenarios/26Change_Material_Global_only_with_Rejections.xml
Mendix/suite/scenarios/27Change_Material_Global_Only_With_Reject_Discard.xml
Mendix/suite/scenarios/28Change MaterialGlobal and Local  with Rejections and Discard NAV.xml
Mendix/suite/scenarios/45Extend same target system - Extend Global for SAP.xml

Committing scripts taken up by sai

Committing scripts 26,27 & 45 with minor change

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialScript.java

Committing changes for script 27

Committing changes for script 27

---

Mendix/suite/scenarios/28Change MaterialGlobal and Local  with Rejections and Discard NAV.xml

Committing code for 28 coding is done and dry run inprogress

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/13.Create Vendor with Questionnaire only Globa Rejections with Discard_SAP.xml
Mendix/suite/scenarios/15.Create_Vendor_with_Save_as_Draft_only_Global_SAP.xml
Mendix/suite/scenarios/24Create_Vendor_with_Questionnaire_with_Global_and_Local_with_Rejections_and_Discard_NAV.xml

Committed the stabilized code for 13 & 15

Sai flows 15.4.19

---

Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/24Create_Vendor_with_Questionnaire_with_Global_and_Local_with_Rejections_and_Discard_NAV.xml

Committing script 24 for vendor discard

Committing script 24 for vendor create reject and discard for NAV

---

Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/28Change MaterialGlobal and Local  with Rejections and Discard NAV.xml

Committing changes for script 28 after communicating with gulnaaz regarding functional break out

Committing changes as communicated by gulnaaz

---

Mendix/MDM_Nav_ItemsCheck/.gitignore
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/34Create with ref Global and local - NAV Direct Copy.xml
Mendix/suite/scenarios/38Create with ref Global and local - NAV Direct Copy with rejections.xml

Committing stabilized code for 34 and 38

Sai flows 22.4.19

---

Mendix/src/com/mendix/test/VendorScript.java
Mendix/src/com/mendix/test/VendorScript_NAV.java
Mendix/suite/scenarios/22.Create_Vendor_with_Questionnaire_with_Global_and_Local_NAV.xml
Mendix/suite/scenarios/38Create with ref Global and local - NAV Direct Copy with rejections.xml
Mendix/suite/scenarios/41Create with ref Global and local - NAV Direct Copy with rejections and discard.xml
Mendix/suite/scenarios/86Change Vendor global and local NAV.xml
Mendix/suite/scenarios/87Change Vendor global and local with Rejections and Discard NAV.xml

Committing 86 and 87 Stabilized code

Committing code for change flow 86 and 87

---

Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/src/com/mendix/test/VendorScript_NAV.java
Mendix/suite/scenarios/87Change Vendor global and local with Rejections and Discard NAV.xml

Committing stabilized script for 87

Committing Script 87 with stabilized code and is ready to run

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/36Create with ref Global and local - Edit Global and Local Data_NAV.xml

Committing minor fix for 34 as normal click is not working during submit

Committing minor fix for 34 as normal click is not working during submit

---

Mendix/suite/scenarios/88Extend Material Global and Local from SAP to  NAV with Rejections and Discard(With Local data adding).xml

minor script changes for 88 to make stabilize

Committing minor changes to script to stabilize script 88

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/88Extend Material Global and Local from SAP to  NAV with Rejections and Discard(With Local data adding).xml

Committing code fixes for script 88

Committing code with fixes to script 88

---

Mendix/src/com/mendix/page/Material_Change_Page.java
Mendix/src/com/mendix/test/MaterialChangeScript.java
Mendix/suite/scenarios/65Extend Material Global and Local from SAP to  JDE with Rejections(With Local data adding).xml

Committing stabilized code for 65

Committing stabilized code for 65

---

Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/74Extend Material Global and Local from SAP to  NAV with Rejections(With Local data adding).xml

Committing stabilized code 74

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/ProceesInfoPage.java
Mendix/suite/scenarios/100Extend Global and Local for NAV.xml

Committing extend script 100 and also fix to failing scripts due to changes xpath's in Code

Committing script 100 and minor fix for failing scripts update

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/Material_JDE_Page.java
Mendix/src/com/mendix/test/MaterialJDEScript.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/MaterialScript.java
Mendix/suite/scenarios/103Extend Global and Local for NAV to JDE(With Local Data Adding)(PA01 SG04).xml
Mendix/suite/scenarios/53Happy Flag for deletion (Not Shared with Multi OpCos)- NAV_Material.xml
Mendix/suite/scenarios/72Extend Vendor Global Only  with Rejections and Discard for SAP (Extend any OpCo to PL) .xml

added code for 53 and 72 scripts

Added missing scripts of 53 and 72 Created and executed now to confirm

---

Mendix/src/com/mendix/test/MaterialJDEScript.java
Mendix/suite/scenarios/103Extend Global and Local for NAV to JDE(With Local Data Adding)(PA01 SG04).xml

Committed implementation script for 103

Committing script 103 with implementation updates

---

Mendix/src/com/mendix/page/Material_Nav_Page.java
Mendix/suite/scenarios/103Extend Global and Local for NAV to JDE(With Local Data Adding)(PA01 SG04).xml

Committing fix for 103

---

Mendix/suite/scenarios/103Extend Global and Local for NAV to JDE(With Local Data Adding)(PA01 SG04).xml

Fixed the issue and is running fine for 103

---

Mendix/src/com/mendix/page/Material_Nav_Page.java

Committing minor fix to switch to Global for 103

Committing minor fix for 103

---

Mendix/src/com/mendix/page/MaterialPage.java

Provided minor fix for to scripts 10 and 12

---

Mendix/src/com/mendix/test/LoginScript.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/70Extend Vendor Global and Local from SAP to  NAV(With Local data adding).xml
Mendix/suite/scenarios/90Extend Vendor Global and Local from JDE to  NAV(With Local data adding).xml

Stabilized code for Extend Vendor from SAP to NAV

Committing the stabilized code for Extend Vendor from SAP to NAV

---

Mendix/suite/scenarios/89Extend Vendor Global and Local from  NAV to JDE (With Local data adding).xml

Updated code to script 89

---

Mendix/src/com/mendix/page/Vendor_JDE_Page.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/src/com/mendix/test/Vendor_JDE_Script.java
Mendix/suite/scenarios/66Extend Material Global and Local from SAP to  JDE(With Local data adding).xml
Mendix/suite/scenarios/89Extend Vendor Global and Local from  NAV to JDE (With Local data adding).xml

Committing fix to 23 and implemented code for 89

Committing fix to 23 and implemented code for 89

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/23.Create_Vendor_with_Questionnaire_with_Global_and_Local_with_Rejections_NAV.xml
Mendix/suite/scenarios/71Extend Vendor Global Only  with Rejections for SAP (Extend any OpCo to PL) .xml

Sai flows 9.5.19

---

Mendix/suite/scenarios/71Extend Vendor Global Only  with Rejections for SAP (Extend any OpCo to PL) .xml

Committing name change for 71

---

Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java

Committing fixes to 89 to make it failure free

---

Mendix/src/com/mendix/page/VendorPage.java

Committing improvement

---

Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/71Extend Vendor Global only with Rejections for SAP any opco to PL.xml

Committing 71 to GIT

---

Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/81Extend Vendor Global and local with Rejections for NAV (For Algeria to panama) .xml
Mendix/suite/scenarios/81Extend vendor Global and Local nav from DZ to PA.xml

Committing fixes to 81 as part of stabilization

Committing fixes to 81 as part of stabilization

---

Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/81Extend vendor Global and Local nav from DZ to PA.xml

Committing improvements to 81

---

Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/80Extend Vendor Global and local with Rejections with Discard for NAV (For Algeria to panama).xml
Mendix/suite/scenarios/81Extend vendor Global and Local nav from DZ to PA with Rejections.xml

Committing stabilized code of 80

Committing stabilized code of 80

---

Mendix/src/com/mendix/page/MaterialApprovalPage.java
Mendix/src/com/mendix/page/MaterialPage.java
Mendix/src/com/mendix/test/MaterialNavScript.java
Mendix/src/com/mendix/test/MaterialScript.java

Committing minor updates to scripts

Committing minor update to scripts

---

Mendix/src/com/mendix/page/VendorPage_NAV.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/22.Create_Vendor_with_Questionnaire_with_Global_and_Local_NAV.xml
Mendix/suite/scenarios/66Extend Material Global and Local from SAP to  JDE(With Local data adding).xml
Mendix/suite/scenarios/96Extend Material Global and Local with Rejections for JDE (Extend KH01 Opco to SG04).xml

Committing minor fixes

---

Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java

Committing minor fix to scenario 15

Sai flows 15.5.19

---

Mendix/src/com/mendix/page/VendorPage.java
Mendix/src/com/mendix/test/VendorScript.java
Mendix/suite/scenarios/16.Create_Vendor_with_Questionnaire_only_Global_with_Rejections.xml

Committing minor fixes for 16

---

Mendix/suite/scenarios/.xml
Mendix/suite/scenarios/108.Create_Material_JDE_with_Questionnaire_Global_And_Local_with_Rejections.xml

Create Material JDE with Rejections

Create_Material_JDE with rejections

---

Mendix/suite/scenarios/38Create with ref Global and local - NAV Direct Copy with rejections.xml

Committing commented GBDA approval level code

Committing commented GBDA approval level
